apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: karydia-default-network-policy-l3
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - podSelector:
        matchLabels: {}
  ingress:
  - from:
    - podSelector:
        matchLabels: {}
