apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: karydia-default-network-policy-l1
spec:
  podSelector:
    matchLabels: {}
  policyTypes:
  - Egress
  - Ingress
  egress:
  - to:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.250.0.0/16 # host network
        - 100.64.0.0/10 # local network
        - 169.254.169.254/32 # meta data service (Azure, AWS, GCP, OpenStack)
        - 100.100.100.200/32 # meta data service (Alicloud)
    - namespaceSelector:
        matchExpressions:
          - {key: name, operator: NotIn, values: [kube-system]}
  ingress:
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
        except:
        - 10.250.0.0/16 # host network
        - 100.64.0.0/10 # local network
        - 169.254.169.254/32 # meta data service (Azure, AWS, GCP, OpenStack)
        - 100.100.100.200/32 # meta data service (Alicloud)
    - namespaceSelector:
        matchExpressions:
          - {key: name, operator: NotIn, values: [kube-system]}
