# Copyright (C) 2019 SAP SE or an SAP affiliate company. All rights reserved.
# This file is licensed under the Apache Software License, v. 2 except as
# noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karydia-view-kc
rules:
- apiGroups: ["karydia.gardener.cloud"]
  resources: ["karydiaconfigs"]
  verbs: ["get", "watch", "list"]

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karydia-networkpolicies
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karydia-view
subjects:
- kind: User
  name: system:karydia
  apiGroup: rbac.authorization.k8s.io
- kind: User
  name: system:kubemgmt
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karydia-networkpolicies
subjects:
- kind: User
  name: system:karydia
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: karydia-networkpolicies
  apiGroup: rbac.authorization.k8s.io

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: karydia-view-kc
subjects:
- kind: User
  name: system:karydia
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: karydia-view-kc
  apiGroup: rbac.authorization.k8s.io

---

# Define role for kube-mgmt to cache the resources
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemgmt-cacher
rules:
- apiGroups: [""]
  resources: ["nodes", "namespaces", "persistentvolumes", "pods", "endpoints"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations", "mutatingwebhookconfigurations"]
  verbs: ["get", "watch", "list"]

---

# Grant kube-mgmt role defined above.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubemgmt-cacher
subjects:
- kind: User
  name: system:kubemgmt
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: kubemgmt-cacher
  apiGroup: rbac.authorization.k8s.io
