apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.metadata.name }}-seccomp
  namespace: kube-system
  labels:
    security: seccomp
    app: {{ .Values.metadata.labelApp }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded, hook-failed
spec:
  selector:
    matchLabels:
      security: seccomp
  template:
    metadata:
      labels:
        security: seccomp
        app: {{ .Values.metadata.labelApp }}
    spec:
      containers:
      - name: {{ .Values.metadata.name }}-seccomp-installer
        image: alpine:3.10.0
        command: ["/bin/sh", "-c", "cp -r -L /seccomp/*.json /host/seccomp/"]
        volumeMounts:
        - name: profiles
          mountPath: /seccomp
        - name: hostseccomp
          mountPath: /host/seccomp
          readOnly: false
      volumes:
      - name: hostseccomp
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: profiles
        configMap:
          name: custom-seccomp-profiles
