{{- $customSeccompProfiles := .Files.Glob "custom-seccomp-profiles/*.json" }}
{{ if $customSeccompProfiles }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.metadata.name }}-seccomp
  namespace: kube-system
  labels:
    security: seccomp
    app: {{ .Values.metadata.labelApp }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  selector:
    matchLabels:
      security: seccomp
  template:
    metadata:
      labels:
        security: seccomp
        app: {{ .Values.metadata.labelApp }}
    spec:
      containers:
      - name: {{ .Values.metadata.name }}-seccomp-installer
        image: alpine:3.10.0
        command: ["/bin/sh", "-c", "cp -r -L /seccomp/*.json /host/seccomp/ && while true; do sleep 3600; done"]
        volumeMounts:
        - name: profiles
          mountPath: /seccomp
        - name: hostseccomp
          mountPath: /host/seccomp
          readOnly: false
      restartPolicy: Always
      volumes:
      - name: hostseccomp
        hostPath:
          path: /var/lib/kubelet/seccomp
      - name: profiles
        configMap:
          name: custom-seccomp-profiles
{{ end }}
