# Copyright (C) 2019 SAP SE or an SAP affiliate company. All rights reserved.
# This file is licensed under the Apache Software License, v. 2 except as
# noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

apiVersion: {{ .Values.deployment.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Values.metadata.name }}
  labels:
    app: {{ .Values.metadata.labelApp }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.metadata.labelApp }}
    spec:
      serviceAccount: {{ .Values.metadata.name }}
      containers:
      - name: {{ .Values.metadata.name }}
        image: {{ .Values.metadata.name }}/{{ .Values.metadata.name }}:{{ .Values.version }}
        imagePullPolicy: IfNotPresent
        command:
          - karydia
          - runserver
          - --tls-cert
          - /etc/karydia/tls/cert.pem
          - --tls-key
          - /etc/karydia/tls/key.pem
          - --enable-default-network-policy
          - --enable-karydia-admission
          - --enable-opa-admission
        volumeMounts:
          - name: {{ .Values.deployment.volume.name }}
            mountPath: {{ .Values.deployment.volume.path }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 33333
            scheme: HTTPS
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
          failureThreshold: 2
        ports:
        - containerPort: 33333
      - name: {{ .Values.namespace.name }}
        image: openpolicyagent/opa:0.10.2
        imagePullPolicy: IfNotPresent
        args:
          - "run"
          - "--server"
          - "--addr=http://127.0.0.1:8181"
      - name: kube-mgmt
        image: openpolicyagent/kube-mgmt:0.7
        imagePullPolicy: Always
        args:
          - "--replicate-cluster=v1/pods"
      initContainers:
      - name: pre-install-{{ .Values.metadata.name }}
        image: lachlanevenson/k8s-kubectl
        command: ['sh', '-c', 'apk add --update --no-cache openssl && sh /tmp/create-karydia-certificate.sh && sh /tmp/create-karydia-tls-secret.sh && sh /tmp/example-default-network-policy.sh']
        volumeMounts:
        - name: workdir
          mountPath: "/tmp"

      volumes:
        - name: {{ .Values.deployment.volume.name }}
          secret:
            secretName: {{ .Values.deployment.volume.name }}
            optional: true
        - name: workdir
          configMap:
            name: karydia-tmp
