# Copyright (C) 2019 SAP SE or an SAP affiliate company. All rights reserved.
# This file is licensed under the Apache Software License, v. 2 except as
# noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.metadata.name }}-post
  labels:
    app: {{ .Values.metadata.labelApp }}
  namespace: {{ .Values.metadata.namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Values.metadata.name }}-post-install
    spec:
      serviceAccountName: karydia
      restartPolicy: OnFailure
      containers:
        - name: {{ .Values.metadata.name }}-post-install-container
          image: "lachlanevenson/k8s-kubectl"
          command: ['sh', '-c', 'sh /tmp/configure-karydia-webhook.sh']
          volumeMounts:
            - mountPath: "/tmp"
              name: workdir
      volumes:
        - name: workdir
          configMap:
            name: karydia-tmp
