# Copyright (C) 2019 SAP SE or an SAP affiliate company. All rights reserved.
# This file is licensed under the Apache Software License, v. 2 except as
# noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccount }}
  namespace: {{ .Values.metadata.namespace }}

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-kc
rules:
- apiGroups: ["karydia.gardener.cloud"]
  resources: ["karydiaconfigs"]
  verbs: ["get", "watch", "list"]

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-knp
rules:
- apiGroups: ["karydia.gardener.cloud"]
  resources: ["karydianetworkpolicies"]
  verbs: ["get", "watch", "list"]

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-networkpolicies
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "watch", "list", "create", "patch", "update", "delete"]

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.rbac.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-networkpolicies
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.rbac.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-networkpolicies
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-kc
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.rbac.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-view-kc
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-knp
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.rbac.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-view-knp
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-roles
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs: ["list"]

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-roles
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.rbac.serviceAccount }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-view-roles
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-installer
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests"]
  verbs: ["create", "delete", "get"]
- apiGroups: ["certificates.k8s.io"]
  resources: ["certificatesigningrequests/approval"]
  verbs: ["update"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "create", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "delete"]
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["validatingwebhookconfigurations"]
  verbs: ["get", "create", "patch", "delete"]
- apiGroups: ["admissionregistration.k8s.io"]
  resources: ["mutatingwebhookconfigurations"]
  verbs: ["get", "create", "patch", "delete"]

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: install-{{ .Values.metadata.name }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.rbac.serviceAccount }}
  namespace: {{ .Values.metadata.namespace }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-installer
  apiGroup: {{ .Values.rbac.apiGroup }}
