# Copyright 2019 Copyright (c) 2019 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: {{ .Values.apiVersion }}
kind: ServiceAccount
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-ksp
rules:
- apiGroups: ["karydia.gardener.cloud"]
  resources: ["karydiasecuritypolicies"]
  verbs: ["get", "watch", "list"]

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-networkpolicies
rules:
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "watch", "list", "create", "patch", "update"]

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.metadata.name }}
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-networkpolicies
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.metadata.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-networkpolicies
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: {{ .Values.metadata.name }}-view-ksp
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.metadata.name }}
roleRef:
  kind: ClusterRole
  name: {{ .Values.metadata.name }}-view-ksp
  apiGroup: {{ .Values.rbac.apiGroup }}

---

kind: ClusterRole
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: { .Values.metadata.name }}-view-roles
rules:
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterroles", "clusterrolebindings", "roles", "rolebindings"]
  verbs: ["list"]

---

kind: ClusterRoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  name: { .Values.metadata.name }}-view-roles
subjects:
- kind: ServiceAccount
  namespace: { .Values.metadata.namespace }}
  name: { .Values.metadata.name }}
roleRef:
  kind: ClusterRole
  name: { .Values.metadata.name }}-view-roles
  apiGroup: {{ .Values.rbac.apiGroup }}

---

# Define role for OPA/kube-mgmt to update configmaps with policy status.
kind: Role
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  namespace: {{ .Values.namespace.name }}
  name: configmap-modifier
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["update", "patch"]

---

# Grant OPA/kube-mgmt role defined above.
kind: RoleBinding
apiVersion: {{ .Values.rbac.apiGroup }}{{ .Values.rbac.apiVersion }}
metadata:
  namespace: {{ .Values.namespace.name }}
  name: {{ .Values.namespace.name }}-configmap-modifier
subjects:
- kind: ServiceAccount
  namespace: {{ .Values.metadata.namespace }}
  name: {{ .Values.metadata.name }}
roleRef:
  kind: Role
  name: configmap-modifier
  apiGroup: {{ .Values.rbac.apiGroup }}
