// Copyright (C) 2019 SAP SE or an SAP affiliate company. All rights reserved.
// This file is licensed under the Apache Software License, v. 2 except as
// noted otherwise in the LICENSE file.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/karydia/karydia/pkg/apis/karydia/v1alpha1"
	scheme "github.com/karydia/karydia/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KarydiaConfigsGetter has a method to return a KarydiaConfigInterface.
// A group's client should implement this interface.
type KarydiaConfigsGetter interface {
	KarydiaConfigs() KarydiaConfigInterface
}

// KarydiaConfigInterface has methods to work with KarydiaConfig resources.
type KarydiaConfigInterface interface {
	Create(*v1alpha1.KarydiaConfig) (*v1alpha1.KarydiaConfig, error)
	Update(*v1alpha1.KarydiaConfig) (*v1alpha1.KarydiaConfig, error)
	UpdateStatus(*v1alpha1.KarydiaConfig) (*v1alpha1.KarydiaConfig, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KarydiaConfig, error)
	List(opts v1.ListOptions) (*v1alpha1.KarydiaConfigList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KarydiaConfig, err error)
	KarydiaConfigExpansion
}

// karydiaConfigs implements KarydiaConfigInterface
type karydiaConfigs struct {
	client rest.Interface
}

// newKarydiaConfigs returns a KarydiaConfigs
func newKarydiaConfigs(c *KarydiaV1alpha1Client) *karydiaConfigs {
	return &karydiaConfigs{
		client: c.RESTClient(),
	}
}

// Get takes name of the karydiaConfig, and returns the corresponding karydiaConfig object, and an error if there is any.
func (c *karydiaConfigs) Get(name string, options v1.GetOptions) (result *v1alpha1.KarydiaConfig, err error) {
	result = &v1alpha1.KarydiaConfig{}
	err = c.client.Get().
		Resource("karydiaconfigs").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KarydiaConfigs that match those selectors.
func (c *karydiaConfigs) List(opts v1.ListOptions) (result *v1alpha1.KarydiaConfigList, err error) {
	result = &v1alpha1.KarydiaConfigList{}
	err = c.client.Get().
		Resource("karydiaconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested karydiaConfigs.
func (c *karydiaConfigs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("karydiaconfigs").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a karydiaConfig and creates it.  Returns the server's representation of the karydiaConfig, and an error, if there is any.
func (c *karydiaConfigs) Create(karydiaConfig *v1alpha1.KarydiaConfig) (result *v1alpha1.KarydiaConfig, err error) {
	result = &v1alpha1.KarydiaConfig{}
	err = c.client.Post().
		Resource("karydiaconfigs").
		Body(karydiaConfig).
		Do().
		Into(result)
	return
}

// Update takes the representation of a karydiaConfig and updates it. Returns the server's representation of the karydiaConfig, and an error, if there is any.
func (c *karydiaConfigs) Update(karydiaConfig *v1alpha1.KarydiaConfig) (result *v1alpha1.KarydiaConfig, err error) {
	result = &v1alpha1.KarydiaConfig{}
	err = c.client.Put().
		Resource("karydiaconfigs").
		Name(karydiaConfig.Name).
		Body(karydiaConfig).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *karydiaConfigs) UpdateStatus(karydiaConfig *v1alpha1.KarydiaConfig) (result *v1alpha1.KarydiaConfig, err error) {
	result = &v1alpha1.KarydiaConfig{}
	err = c.client.Put().
		Resource("karydiaconfigs").
		Name(karydiaConfig.Name).
		SubResource("status").
		Body(karydiaConfig).
		Do().
		Into(result)
	return
}

// Delete takes name of the karydiaConfig and deletes it. Returns an error if one occurs.
func (c *karydiaConfigs) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("karydiaconfigs").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *karydiaConfigs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("karydiaconfigs").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched karydiaConfig.
func (c *karydiaConfigs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KarydiaConfig, err error) {
	result = &v1alpha1.KarydiaConfig{}
	err = c.client.Patch(pt).
		Resource("karydiaconfigs").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
