/*
Copyright 2019 (c) 2018 SAP SE or an SAP affiliate company. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/karydia/karydia/pkg/apis/karydia/v1alpha1"
	scheme "github.com/karydia/karydia/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// KarydiaSecurityPoliciesGetter has a method to return a KarydiaSecurityPolicyInterface.
// A group's client should implement this interface.
type KarydiaSecurityPoliciesGetter interface {
	KarydiaSecurityPolicies() KarydiaSecurityPolicyInterface
}

// KarydiaSecurityPolicyInterface has methods to work with KarydiaSecurityPolicy resources.
type KarydiaSecurityPolicyInterface interface {
	Create(*v1alpha1.KarydiaSecurityPolicy) (*v1alpha1.KarydiaSecurityPolicy, error)
	Update(*v1alpha1.KarydiaSecurityPolicy) (*v1alpha1.KarydiaSecurityPolicy, error)
	UpdateStatus(*v1alpha1.KarydiaSecurityPolicy) (*v1alpha1.KarydiaSecurityPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.KarydiaSecurityPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.KarydiaSecurityPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KarydiaSecurityPolicy, err error)
	KarydiaSecurityPolicyExpansion
}

// karydiaSecurityPolicies implements KarydiaSecurityPolicyInterface
type karydiaSecurityPolicies struct {
	client rest.Interface
}

// newKarydiaSecurityPolicies returns a KarydiaSecurityPolicies
func newKarydiaSecurityPolicies(c *KarydiaV1alpha1Client) *karydiaSecurityPolicies {
	return &karydiaSecurityPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the karydiaSecurityPolicy, and returns the corresponding karydiaSecurityPolicy object, and an error if there is any.
func (c *karydiaSecurityPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	result = &v1alpha1.KarydiaSecurityPolicy{}
	err = c.client.Get().
		Resource("karydiasecuritypolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of KarydiaSecurityPolicies that match those selectors.
func (c *karydiaSecurityPolicies) List(opts v1.ListOptions) (result *v1alpha1.KarydiaSecurityPolicyList, err error) {
	result = &v1alpha1.KarydiaSecurityPolicyList{}
	err = c.client.Get().
		Resource("karydiasecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested karydiaSecurityPolicies.
func (c *karydiaSecurityPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("karydiasecuritypolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a karydiaSecurityPolicy and creates it.  Returns the server's representation of the karydiaSecurityPolicy, and an error, if there is any.
func (c *karydiaSecurityPolicies) Create(karydiaSecurityPolicy *v1alpha1.KarydiaSecurityPolicy) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	result = &v1alpha1.KarydiaSecurityPolicy{}
	err = c.client.Post().
		Resource("karydiasecuritypolicies").
		Body(karydiaSecurityPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a karydiaSecurityPolicy and updates it. Returns the server's representation of the karydiaSecurityPolicy, and an error, if there is any.
func (c *karydiaSecurityPolicies) Update(karydiaSecurityPolicy *v1alpha1.KarydiaSecurityPolicy) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	result = &v1alpha1.KarydiaSecurityPolicy{}
	err = c.client.Put().
		Resource("karydiasecuritypolicies").
		Name(karydiaSecurityPolicy.Name).
		Body(karydiaSecurityPolicy).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *karydiaSecurityPolicies) UpdateStatus(karydiaSecurityPolicy *v1alpha1.KarydiaSecurityPolicy) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	result = &v1alpha1.KarydiaSecurityPolicy{}
	err = c.client.Put().
		Resource("karydiasecuritypolicies").
		Name(karydiaSecurityPolicy.Name).
		SubResource("status").
		Body(karydiaSecurityPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the karydiaSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *karydiaSecurityPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("karydiasecuritypolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *karydiaSecurityPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("karydiasecuritypolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched karydiaSecurityPolicy.
func (c *karydiaSecurityPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	result = &v1alpha1.KarydiaSecurityPolicy{}
	err = c.client.Patch(pt).
		Resource("karydiasecuritypolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
