/*
Copyright The Karydia Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/kinvolk/karydia/pkg/apis/karydia/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeKarydiaSecurityPolicies implements KarydiaSecurityPolicyInterface
type FakeKarydiaSecurityPolicies struct {
	Fake *FakeKarydiaV1alpha1
}

var karydiasecuritypoliciesResource = schema.GroupVersionResource{Group: "karydia.gardener.cloud", Version: "v1alpha1", Resource: "karydiasecuritypolicies"}

var karydiasecuritypoliciesKind = schema.GroupVersionKind{Group: "karydia.gardener.cloud", Version: "v1alpha1", Kind: "KarydiaSecurityPolicy"}

// Get takes name of the karydiaSecurityPolicy, and returns the corresponding karydiaSecurityPolicy object, and an error if there is any.
func (c *FakeKarydiaSecurityPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(karydiasecuritypoliciesResource, name), &v1alpha1.KarydiaSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KarydiaSecurityPolicy), err
}

// List takes label and field selectors, and returns the list of KarydiaSecurityPolicies that match those selectors.
func (c *FakeKarydiaSecurityPolicies) List(opts v1.ListOptions) (result *v1alpha1.KarydiaSecurityPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(karydiasecuritypoliciesResource, karydiasecuritypoliciesKind, opts), &v1alpha1.KarydiaSecurityPolicyList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.KarydiaSecurityPolicyList{ListMeta: obj.(*v1alpha1.KarydiaSecurityPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.KarydiaSecurityPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested karydiaSecurityPolicies.
func (c *FakeKarydiaSecurityPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(karydiasecuritypoliciesResource, opts))
}

// Create takes the representation of a karydiaSecurityPolicy and creates it.  Returns the server's representation of the karydiaSecurityPolicy, and an error, if there is any.
func (c *FakeKarydiaSecurityPolicies) Create(karydiaSecurityPolicy *v1alpha1.KarydiaSecurityPolicy) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(karydiasecuritypoliciesResource, karydiaSecurityPolicy), &v1alpha1.KarydiaSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KarydiaSecurityPolicy), err
}

// Update takes the representation of a karydiaSecurityPolicy and updates it. Returns the server's representation of the karydiaSecurityPolicy, and an error, if there is any.
func (c *FakeKarydiaSecurityPolicies) Update(karydiaSecurityPolicy *v1alpha1.KarydiaSecurityPolicy) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(karydiasecuritypoliciesResource, karydiaSecurityPolicy), &v1alpha1.KarydiaSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KarydiaSecurityPolicy), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeKarydiaSecurityPolicies) UpdateStatus(karydiaSecurityPolicy *v1alpha1.KarydiaSecurityPolicy) (*v1alpha1.KarydiaSecurityPolicy, error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateSubresourceAction(karydiasecuritypoliciesResource, "status", karydiaSecurityPolicy), &v1alpha1.KarydiaSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KarydiaSecurityPolicy), err
}

// Delete takes name of the karydiaSecurityPolicy and deletes it. Returns an error if one occurs.
func (c *FakeKarydiaSecurityPolicies) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(karydiasecuritypoliciesResource, name), &v1alpha1.KarydiaSecurityPolicy{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeKarydiaSecurityPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(karydiasecuritypoliciesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.KarydiaSecurityPolicyList{})
	return err
}

// Patch applies the patch and returns the patched karydiaSecurityPolicy.
func (c *FakeKarydiaSecurityPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.KarydiaSecurityPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(karydiasecuritypoliciesResource, name, data, subresources...), &v1alpha1.KarydiaSecurityPolicy{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.KarydiaSecurityPolicy), err
}
