#!/bin/bash

# Copyright (C) 2019 SAP SE or an SAP affiliate company. All rights reserved.
# This file is licensed under the Apache Software License, v. 2 except as
# noted otherwise in the LICENSE file.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Parameter(s)
if [[ -z "$1" ]]
then
  echo "Usage: $0 USERNAME"
  exit 1
fi
user=$1
outdir=./.user.kube
echo 'Execution...'
echo

# Collect cluster information
context=$(kubectl config current-context)
cluster=$(kubectl config view -o jsonpath="{.contexts[?(@.name==\"${context}\")].context.cluster}")
server=$(kubectl config view -o jsonpath="{.clusters[?(@.name==\"${cluster}\")].cluster.server}")
usrctx="${context}-user-${user}"

# Create & collect user information
cacrtfile=${outdir}/${usrctx}.ca.crt
mkdir -p ${outdir}
kubectl create serviceaccount "${user}"
secret=$(kubectl get serviceaccount "${user}" -o jsonpath='{.secrets[0].name}')
token=$(kubectl get secret "${secret}" -o jsonpath='{.data.token}' | base64 --decode)
kubectl get secret "${secret}" -o jsonpath='{.data.ca\.crt}' | base64 --decode > ${cacrtfile}

# Restrict user's permissions
cat <<EOF | kubectl create -f -
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: view-${user}-global
subjects:
- kind: ServiceAccount
  name: ${user}
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
EOF

# Create user's kubeconfig
kubeconfigfile=${outdir}/${usrctx}.kubeconfig
KUBECONFIG=${kubeconfigfile} kubectl config set-cluster "${cluster}" \
  --embed-certs=true \
  --certificate-authority="${cacrtfile}" \
  --server="${server}"
KUBECONFIG=${kubeconfigfile} kubectl config set-credentials "${usrctx}" \
  --token="${token}"
KUBECONFIG=${kubeconfigfile} kubectl config set-context "${usrctx}" \
  --cluster="${cluster}" \
  --user="${usrctx}"
KUBECONFIG=${kubeconfigfile} kubectl config use-context "${usrctx}"

# Clean up
rm -f ${cacrtfile}

echo
echo "Done. Test with:"
echo "export KUBECONFIG=${kubeconfigfile}"

