#!/bin/bash
echo "Start installing Karydia on your cluster"
echo "Provide Tiller on the server to use Helm later..."
kubectl apply -f helm-service-account.yaml
helm init --service-account tiller
echo "Installed Tiller"

sleep 10

echo "Create your TLS certificates..."
/bin/bash ../scripts/create-karydia-certificate
/bin/bash ../scripts/create-karydia-tls-secret
echo "Created certificates"

sleep 1

echo "Deploy Karydia..."
kubectl create configmap -n kube-system karydia-default-network-policy --from-literal policy="$(<../manifests/example-default-network-policy.yml)"
helm install ./ --name karydia
echo "Deployed Karydia"

sleep 10

echo "Establish Webhook..."
/bin/bash ../scripts/configure-karydia-webhook
echo "Established Webhook"
